export type FilterType = {
  listingType: string | null;
  state: string | null;
  propertyType: string | null;
  propertyTypeId?: string | null;
  roomAsText: string | null;
  categoryId?: string | null;
  minPrice?: number | null;
  maxPrice?: number | null;
  roomCount?: number | null;
  bathroomCount?: number | null;
  minProjectArea?: number | null;
  maxProjectArea?: number | null;
  interiorFeatureIds?: string[] | null;
  exteriorFeatureIds?: string[] | null;
  accessibilityFeatureIds?: string[] | null;
  faceFeatureIds?: string[] | null;
  infrastructureFeatureIds?: string[] | null;
  sceneryFeatureIds?: string[] | null;
  locationFeatureIds?: string[] | null;
  isNewSelected?: boolean | null;
  isOnePlusOneSelected?: boolean | null;
  isTwoPlusOneSelected?: boolean | null;
  isThreePlusOneSelected?: boolean | null;
};
